name: Update UTS Timetable

on:
  schedule:
    - cron: "0 */6 * * *"  # **每 6 小时运行一次**
  workflow_dispatch:  # **允许手动触发**

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # **避免使用默认身份**

      - name: Setup Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install requests icalendar pytz

      - name: Run Python Script to Generate ICS
        run: python scripts/update_calendar.py  # **运行你的 Python 代码**

      - name: Check for Changes
        id: check_changes
        run: |
          git add filtered_calendar.ics
          if git diff --cached --quiet; then
            echo "No changes detected."
            echo "CHANGES=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "CHANGES=true" >> $GITHUB_ENV
          fi

          
      - name: Commit and Push Changes
        if: env.CHANGES == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git commit -m "Auto update UTS Timetable" || echo "No changes to commit"
          git branch -M main
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin main
